version: '3.8'

services:
  app:
    container_name: toolbox-ui
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
